<a href="https://colab.research.google.com/github/hara0-tavares/Projeto4/blob/main/Projeto4.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

##Analisando os Dados da ANP

In [ ]:
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib as plt

In [ ]:
df_junho = pd.read_csv('https://www.gov.br/anp/pt-br/centrais-de-conteudo/dados-abertos/arquivos/shpc/dsan/2021/2021-06-gasolina-etanol.csv', sep=';')

In [ ]:
df_julho = pd.read_csv('https://www.gov.br/anp/pt-br/centrais-de-conteudo/dados-abertos/arquivos/shpc/dsan/2021/2021-07-gasolina-etanol.csv', sep=';')

In [ ]:
dataframe = pd.concat([df_junho, df_julho], ignore_index =True)
dataframe

,Região - Sigla,Estado - Sigla,Município,Revenda,CNPJ da Revenda,Nome da Rua,Número Rua,Complemento,Bairro,Cep,Produto,Data da Coleta,Valor de Venda,Valor de Compra,Unidade de Medida,Bandeira
0,N,AC,CRUZEIRO DO SUL,CARDINAL E OLIVEIRA LTDA,03.608.766/0005-75,AVENIDA BOULEVARD THAUMATURGO,1031,NaN,CENTRO,69980-000,GASOLINA,02/06/2021,"6,89",NaN,R$ / litro,PETROBRAS DISTRIBUIDORA S.A.
1,N,AC,CRUZEIRO DO SUL,CARDINAL E OLIVEIRA LTDA,03.608.766/0005-75,AVENIDA BOULEVARD THAUMATURGO,1031,NaN,CENTRO,69980-000,GASOLINA ADITIVADA,02/06/2021,"6,89",NaN,R$ / litro,PETROBRAS DISTRIBUIDORA S.A.
2,N,AC,CRUZEIRO DO SUL,CARDINAL E OLIVEIRA LTDA,03.608.766/0006-56,AVENIDA 25 DE AGOSTO,1350,NaN,25 DE AGOSTO,69980-000,ETANOL,01/06/2021,"6,1",NaN,R$ / litro,PETROBRAS DISTRIBUIDORA S.A.
3,N,AC,CRUZEIRO DO SUL,CARDINAL E OLIVEIRA LTDA,03.608.766/0006-56,AVENIDA 25 DE AGOSTO,1350,NaN,25 DE AGOSTO,69980-000,GASOLINA,01/06/2021,"6,89",NaN,R$ / litro,PETROBRAS DISTRIBUIDORA S.A.
4,N,AC,CRUZEIRO DO SUL,CARDINAL E OLIVEIRA LTDA,03.608.766/0004-94,AVENIDA LAURO MULLER,943,NaN,JOÃO ALVES,69980-000,GASOLINA,02/06/2021,"6,89",NaN,R$ / litro,BRANCA
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
97581,SE,ES,ARACRUZ,POSTO DE COMBUSTIVEL SHOW EIRELI,23.797.660/0001-40,AVENIDA CORONEL VENANCIO FLORES,28,NaN,CENTRO,29190-010,GASOLINA ADITIVADA,26/07/2021,"5,87",NaN,R$ / litro,BRANCA
97582,SE,ES,ARACRUZ,POSTO DE COMBUSTIVEL SHOW EIRELI,23.797.660/0001-40,AVENIDA CORONEL VENANCIO FLORES,28,NaN,CENTRO,29190-010,ETANOL,26/07/2021,"4,99",NaN,R$ / litro,BRANCA
97583,SE,ES,ARACRUZ,POSTO DE COMBUSTIVEL SHOW EIRELI,23.797.660/0001-40,AVENIDA CORONEL VENANCIO FLORES,28,NaN,CENTRO,29190-010,GASOLINA,26/07/2021,"5,87",NaN,R$ / litro,BRANCA
97584,SE,MG,ARAXA,AUTO POSTO BRANQUINHO LTDA,37.461.683/0001-94,AVENIDA SENADOR MONTANDON,950,NaN,CENTRO,38183-214,ETANOL,28/07/2021,"4,599",NaN,R$ / litro,RIO BRANCO
97585,SE,MG,ARAXA,AUTO POSTO BRANQUINHO LTDA,37.461.683/0001-94,AVENIDA SENADOR MONTANDON,950,NaN,CENTRO,38183-214,GASOLINA,28/07/2021,"6,199",NaN,R$ / litro,RIO BRANCO

##Analise dos dados da tabela(Entendendo os dados que iremos utilizar).

In [ ]:
dataframe.shape

(97586, 16)

In [ ]:
dataframe.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 97586 entries, 0 to 97585
Data columns (total 16 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   Região - Sigla     97586 non-null  object
 1   Estado - Sigla     97586 non-null  object
 2   Município          97586 non-null  object
 3   Revenda            97586 non-null  object
 4   CNPJ da Revenda    97586 non-null  object
 5   Nome da Rua        97586 non-null  object
 6   Número Rua         97529 non-null  object
 7   Complemento        19711 non-null  object
 8   Bairro             97327 non-null  object
 9   Cep                97586 non-null  object
 10  Produto            97586 non-null  object
 11  Data da Coleta     97586 non-null  object
 12  Valor de Venda     97586 non-null  object
 13  Valor de Compra    0 non-null      float64
 14  Unidade de Medida  97586 non-null  object
 15  Bandeira           97586 non-null  object
dtypes: float64(1), object(15)
memory usage: 11.9+ MB

In [ ]:
dataframe['Valor de Venda'].describe()

count     97586
unique     1628
top       5,599
freq       3256
Name: Valor de Venda, dtype: object

##Limpeza dos dados.

In [ ]:
df_copia = dataframe.copy()
df_copia

,Região - Sigla,Estado - Sigla,Município,Revenda,CNPJ da Revenda,Nome da Rua,Número Rua,Complemento,Bairro,Cep,Produto,Data da Coleta,Valor de Venda,Valor de Compra,Unidade de Medida,Bandeira
0,N,AC,CRUZEIRO DO SUL,CARDINAL E OLIVEIRA LTDA,03.608.766/0005-75,AVENIDA BOULEVARD THAUMATURGO,1031,NaN,CENTRO,69980-000,GASOLINA,02/06/2021,"6,89",NaN,R$ / litro,PETROBRAS DISTRIBUIDORA S.A.
1,N,AC,CRUZEIRO DO SUL,CARDINAL E OLIVEIRA LTDA,03.608.766/0005-75,AVENIDA BOULEVARD THAUMATURGO,1031,NaN,CENTRO,69980-000,GASOLINA ADITIVADA,02/06/2021,"6,89",NaN,R$ / litro,PETROBRAS DISTRIBUIDORA S.A.
2,N,AC,CRUZEIRO DO SUL,CARDINAL E OLIVEIRA LTDA,03.608.766/0006-56,AVENIDA 25 DE AGOSTO,1350,NaN,25 DE AGOSTO,69980-000,ETANOL,01/06/2021,"6,1",NaN,R$ / litro,PETROBRAS DISTRIBUIDORA S.A.
3,N,AC,CRUZEIRO DO SUL,CARDINAL E OLIVEIRA LTDA,03.608.766/0006-56,AVENIDA 25 DE AGOSTO,1350,NaN,25 DE AGOSTO,69980-000,GASOLINA,01/06/2021,"6,89",NaN,R$ / litro,PETROBRAS DISTRIBUIDORA S.A.
4,N,AC,CRUZEIRO DO SUL,CARDINAL E OLIVEIRA LTDA,03.608.766/0004-94,AVENIDA LAURO MULLER,943,NaN,JOÃO ALVES,69980-000,GASOLINA,02/06/2021,"6,89",NaN,R$ / litro,BRANCA
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
97581,SE,ES,ARACRUZ,POSTO DE COMBUSTIVEL SHOW EIRELI,23.797.660/0001-40,AVENIDA CORONEL VENANCIO FLORES,28,NaN,CENTRO,29190-010,GASOLINA ADITIVADA,26/07/2021,"5,87",NaN,R$ / litro,BRANCA
97582,SE,ES,ARACRUZ,POSTO DE COMBUSTIVEL SHOW EIRELI,23.797.660/0001-40,AVENIDA CORONEL VENANCIO FLORES,28,NaN,CENTRO,29190-010,ETANOL,26/07/2021,"4,99",NaN,R$ / litro,BRANCA
97583,SE,ES,ARACRUZ,POSTO DE COMBUSTIVEL SHOW EIRELI,23.797.660/0001-40,AVENIDA CORONEL VENANCIO FLORES,28,NaN,CENTRO,29190-010,GASOLINA,26/07/2021,"5,87",NaN,R$ / litro,BRANCA
97584,SE,MG,ARAXA,AUTO POSTO BRANQUINHO LTDA,37.461.683/0001-94,AVENIDA SENADOR MONTANDON,950,NaN,CENTRO,38183-214,ETANOL,28/07/2021,"4,599",NaN,R$ / litro,RIO BRANCO
97585,SE,MG,ARAXA,AUTO POSTO BRANQUINHO LTDA,37.461.683/0001-94,AVENIDA SENADOR MONTANDON,950,NaN,CENTRO,38183-214,GASOLINA,28/07/2021,"6,199",NaN,R$ / litro,RIO BRANCO

In [ ]:
df_copia['Valor de Venda'] = df_copia['Valor de Venda'].astype(str)
df_copia['Valor de Venda'] = df_copia['Valor de Venda'].str.replace(',','.')
df_copia['Valor de Venda']

0         6.89
1         6.89
2          6.1
3         6.89
4         6.89
         ...
97581     5.87
97582     4.99
97583     5.87
97584    4.599
97585    6.199
Name: Valor de Venda, Length: 97586, dtype: object

In [ ]:
df_copia['Valor de Venda'] = df_copia['Valor de Venda'].astype(float)
df_copia['Valor de Venda']

0        6.890
1        6.890
2        6.100
3        6.890
4        6.890
         ...
97581    5.870
97582    4.990
97583    5.870
97584    4.599
97585    6.199
Name: Valor de Venda, Length: 97586, dtype: float64

In [ ]:
df_copia['Valor de Venda'] = df_copia['Valor de Venda'].apply(lambda x: '%.2f' % x)
df_copia

,Região - Sigla,Estado - Sigla,Município,Revenda,CNPJ da Revenda,Nome da Rua,Número Rua,Complemento,Bairro,Cep,Produto,Data da Coleta,Valor de Venda,Valor de Compra,Unidade de Medida,Bandeira
0,N,AC,CRUZEIRO DO SUL,CARDINAL E OLIVEIRA LTDA,03.608.766/0005-75,AVENIDA BOULEVARD THAUMATURGO,1031,NaN,CENTRO,69980-000,GASOLINA,02/06/2021,6.89,NaN,R$ / litro,PETROBRAS DISTRIBUIDORA S.A.
1,N,AC,CRUZEIRO DO SUL,CARDINAL E OLIVEIRA LTDA,03.608.766/0005-75,AVENIDA BOULEVARD THAUMATURGO,1031,NaN,CENTRO,69980-000,GASOLINA ADITIVADA,02/06/2021,6.89,NaN,R$ / litro,PETROBRAS DISTRIBUIDORA S.A.
2,N,AC,CRUZEIRO DO SUL,CARDINAL E OLIVEIRA LTDA,03.608.766/0006-56,AVENIDA 25 DE AGOSTO,1350,NaN,25 DE AGOSTO,69980-000,ETANOL,01/06/2021,6.10,NaN,R$ / litro,PETROBRAS DISTRIBUIDORA S.A.
3,N,AC,CRUZEIRO DO SUL,CARDINAL E OLIVEIRA LTDA,03.608.766/0006-56,AVENIDA 25 DE AGOSTO,1350,NaN,25 DE AGOSTO,69980-000,GASOLINA,01/06/2021,6.89,NaN,R$ / litro,PETROBRAS DISTRIBUIDORA S.A.
4,N,AC,CRUZEIRO DO SUL,CARDINAL E OLIVEIRA LTDA,03.608.766/0004-94,AVENIDA LAURO MULLER,943,NaN,JOÃO ALVES,69980-000,GASOLINA,02/06/2021,6.89,NaN,R$ / litro,BRANCA
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
97581,SE,ES,ARACRUZ,POSTO DE COMBUSTIVEL SHOW EIRELI,23.797.660/0001-40,AVENIDA CORONEL VENANCIO FLORES,28,NaN,CENTRO,29190-010,GASOLINA ADITIVADA,26/07/2021,5.87,NaN,R$ / litro,BRANCA
97582,SE,ES,ARACRUZ,POSTO DE COMBUSTIVEL SHOW EIRELI,23.797.660/0001-40,AVENIDA CORONEL VENANCIO FLORES,28,NaN,CENTRO,29190-010,ETANOL,26/07/2021,4.99,NaN,R$ / litro,BRANCA
97583,SE,ES,ARACRUZ,POSTO DE COMBUSTIVEL SHOW EIRELI,23.797.660/0001-40,AVENIDA CORONEL VENANCIO FLORES,28,NaN,CENTRO,29190-010,GASOLINA,26/07/2021,5.87,NaN,R$ / litro,BRANCA
97584,SE,MG,ARAXA,AUTO POSTO BRANQUINHO LTDA,37.461.683/0001-94,AVENIDA SENADOR MONTANDON,950,NaN,CENTRO,38183-214,ETANOL,28/07/2021,4.60,NaN,R$ / litro,RIO BRANCO
97585,SE,MG,ARAXA,AUTO POSTO BRANQUINHO LTDA,37.461.683/0001-94,AVENIDA SENADOR MONTANDON,950,NaN,CENTRO,38183-214,GASOLINA,28/07/2021,6.20,NaN,R$ / litro,RIO BRANCO

In [ ]:
df_copia.drop('Valor de Compra', axis='columns', inplace=True)
df_copia.drop('Complemento', axis='columns', inplace=True)

In [ ]:
df_copia

,Região - Sigla,Estado - Sigla,Município,Revenda,CNPJ da Revenda,Nome da Rua,Número Rua,Complemento,Bairro,Cep,Produto,Data da Coleta,Valor de Venda,Valor de Compra,Unidade de Medida,Bandeira
0,N,AC,CRUZEIRO DO SUL,CARDINAL E OLIVEIRA LTDA,03.608.766/0005-75,AVENIDA BOULEVARD THAUMATURGO,1031,NaN,CENTRO,69980-000,GASOLINA,02/06/2021,6.89,NaN,R$ / litro,PETROBRAS DISTRIBUIDORA S.A.
1,N,AC,CRUZEIRO DO SUL,CARDINAL E OLIVEIRA LTDA,03.608.766/0005-75,AVENIDA BOULEVARD THAUMATURGO,1031,NaN,CENTRO,69980-000,GASOLINA ADITIVADA,02/06/2021,6.89,NaN,R$ / litro,PETROBRAS DISTRIBUIDORA S.A.
2,N,AC,CRUZEIRO DO SUL,CARDINAL E OLIVEIRA LTDA,03.608.766/0006-56,AVENIDA 25 DE AGOSTO,1350,NaN,25 DE AGOSTO,69980-000,ETANOL,01/06/2021,6.10,NaN,R$ / litro,PETROBRAS DISTRIBUIDORA S.A.
3,N,AC,CRUZEIRO DO SUL,CARDINAL E OLIVEIRA LTDA,03.608.766/0006-56,AVENIDA 25 DE AGOSTO,1350,NaN,25 DE AGOSTO,69980-000,GASOLINA,01/06/2021,6.89,NaN,R$ / litro,PETROBRAS DISTRIBUIDORA S.A.
4,N,AC,CRUZEIRO DO SUL,CARDINAL E OLIVEIRA LTDA,03.608.766/0004-94,AVENIDA LAURO MULLER,943,NaN,JOÃO ALVES,69980-000,GASOLINA,02/06/2021,6.89,NaN,R$ / litro,BRANCA
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
97581,SE,ES,ARACRUZ,POSTO DE COMBUSTIVEL SHOW EIRELI,23.797.660/0001-40,AVENIDA CORONEL VENANCIO FLORES,28,NaN,CENTRO,29190-010,GASOLINA ADITIVADA,26/07/2021,5.87,NaN,R$ / litro,BRANCA
97582,SE,ES,ARACRUZ,POSTO DE COMBUSTIVEL SHOW EIRELI,23.797.660/0001-40,AVENIDA CORONEL VENANCIO FLORES,28,NaN,CENTRO,29190-010,ETANOL,26/07/2021,4.99,NaN,R$ / litro,BRANCA
97583,SE,ES,ARACRUZ,POSTO DE COMBUSTIVEL SHOW EIRELI,23.797.660/0001-40,AVENIDA CORONEL VENANCIO FLORES,28,NaN,CENTRO,29190-010,GASOLINA,26/07/2021,5.87,NaN,R$ / litro,BRANCA
97584,SE,MG,ARAXA,AUTO POSTO BRANQUINHO LTDA,37.461.683/0001-94,AVENIDA SENADOR MONTANDON,950,NaN,CENTRO,38183-214,ETANOL,28/07/2021,4.60,NaN,R$ / litro,RIO BRANCO
97585,SE,MG,ARAXA,AUTO POSTO BRANQUINHO LTDA,37.461.683/0001-94,AVENIDA SENADOR MONTANDON,950,NaN,CENTRO,38183-214,GASOLINA,28/07/2021,6.20,NaN,R$ / litro,RIO BRANCO

In [ ]:
df_copia['Número Rua'] = df_copia['Número Rua'].astype(str)
df_copia['Número Rua'] = df_copia['Número Rua'].str.replace(',', '')
df_copia['Número Rua']

0        1031
1        1031
2        1350
3        1350
4         943
         ...
97581      28
97582      28
97583      28
97584     950
97585     950
Name: Número Rua, Length: 97586, dtype: object

In [ ]:
df_copia = df_copia.rename(columns={'Região - Sigla':'Região_Sigla', 'Estado - Sigla':'Estado_Sigla', 'CNPJ da Revenda':'CNPJ_Revenda', 'Nome da Rua':'Nome_Rua', 'Número Rua':'Número_Rua', 'Data da Coleta':'Data_Coleta', 'Valor de Venda':'Valor_Venda', 'Unidade de Medida':'Unidade_de_Medida'})
df_copia

,Região_Sigla,Estado_Sigla,Município,Revenda,CNPJ_Revenda,Nome_Rua,Número_Rua,Complemento,Bairro,Cep,Produto,Data_Coleta,Valor_Venda,Valor de Compra,Unidade_de_Medida,Bandeira
0,N,AC,CRUZEIRO DO SUL,CARDINAL E OLIVEIRA LTDA,03.608.766/0005-75,AVENIDA BOULEVARD THAUMATURGO,1031,NaN,CENTRO,69980-000,GASOLINA,02/06/2021,6.89,NaN,R$ / litro,PETROBRAS DISTRIBUIDORA S.A.
1,N,AC,CRUZEIRO DO SUL,CARDINAL E OLIVEIRA LTDA,03.608.766/0005-75,AVENIDA BOULEVARD THAUMATURGO,1031,NaN,CENTRO,69980-000,GASOLINA ADITIVADA,02/06/2021,6.89,NaN,R$ / litro,PETROBRAS DISTRIBUIDORA S.A.
2,N,AC,CRUZEIRO DO SUL,CARDINAL E OLIVEIRA LTDA,03.608.766/0006-56,AVENIDA 25 DE AGOSTO,1350,NaN,25 DE AGOSTO,69980-000,ETANOL,01/06/2021,6.10,NaN,R$ / litro,PETROBRAS DISTRIBUIDORA S.A.
3,N,AC,CRUZEIRO DO SUL,CARDINAL E OLIVEIRA LTDA,03.608.766/0006-56,AVENIDA 25 DE AGOSTO,1350,NaN,25 DE AGOSTO,69980-000,GASOLINA,01/06/2021,6.89,NaN,R$ / litro,PETROBRAS DISTRIBUIDORA S.A.
4,N,AC,CRUZEIRO DO SUL,CARDINAL E OLIVEIRA LTDA,03.608.766/0004-94,AVENIDA LAURO MULLER,943,NaN,JOÃO ALVES,69980-000,GASOLINA,02/06/2021,6.89,NaN,R$ / litro,BRANCA
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
97581,SE,ES,ARACRUZ,POSTO DE COMBUSTIVEL SHOW EIRELI,23.797.660/0001-40,AVENIDA CORONEL VENANCIO FLORES,28,NaN,CENTRO,29190-010,GASOLINA ADITIVADA,26/07/2021,5.87,NaN,R$ / litro,BRANCA
97582,SE,ES,ARACRUZ,POSTO DE COMBUSTIVEL SHOW EIRELI,23.797.660/0001-40,AVENIDA CORONEL VENANCIO FLORES,28,NaN,CENTRO,29190-010,ETANOL,26/07/2021,4.99,NaN,R$ / litro,BRANCA
97583,SE,ES,ARACRUZ,POSTO DE COMBUSTIVEL SHOW EIRELI,23.797.660/0001-40,AVENIDA CORONEL VENANCIO FLORES,28,NaN,CENTRO,29190-010,GASOLINA,26/07/2021,5.87,NaN,R$ / litro,BRANCA
97584,SE,MG,ARAXA,AUTO POSTO BRANQUINHO LTDA,37.461.683/0001-94,AVENIDA SENADOR MONTANDON,950,NaN,CENTRO,38183-214,ETANOL,28/07/2021,4.60,NaN,R$ / litro,RIO BRANCO
97585,SE,MG,ARAXA,AUTO POSTO BRANQUINHO LTDA,37.461.683/0001-94,AVENIDA SENADOR MONTANDON,950,NaN,CENTRO,38183-214,GASOLINA,28/07/2021,6.20,NaN,R$ / litro,RIO BRANCO

In [ ]:
df_copia['Valor_Venda'] = df_copia['Valor_Venda'].astype(float)
df_copia['Valor_Venda']

0        6.89
1        6.89
2        6.10
3        6.89
4        6.89
         ...
97581    5.87
97582    4.99
97583    5.87
97584    4.60
97585    6.20
Name: Valor_Venda, Length: 97586, dtype: float64

###Respondendo As Analises

Qual o preço médio da gasolina e do etanol nesses dois meses?

In [ ]:
valor_medio_produto_df = df_copia.groupby('Produto')['Valor_Venda'].mean().map('R$ {:.2f}'.format)
valor_medio_produto_df[:2]
media_dois_meses = pd.DataFrame(valor_medio_produto_df)
media_dois_meses.rename
media_dois_meses.T

Produto       ETANOL GASOLINA GASOLINA ADITIVADA
Valor_Venda  R$ 4.58  R$ 5.74            R$ 5.88

Qual o preço médio da gasolina e do etanol por estado?

In [ ]:
preço_medio = df_copia.groupby(['Produto', 'Estado_Sigla']).mean()
preço_medio['Valor_Venda'] = preço_medio['Valor_Venda'].map('R$ {:.2f}'.format)
preço_medio.unstack()[:2].T

Produto                        ETANOL GASOLINA
                Estado_Sigla
Valor_Venda     AC            R$ 5.54  R$ 6.44
                AL            R$ 5.19  R$ 5.96
                AM            R$ 4.45  R$ 5.56
                AP            R$ 5.31  R$ 4.99
                BA            R$ 4.94  R$ 5.96
                CE            R$ 5.20  R$ 5.81
                DF            R$ 4.89  R$ 5.86
                ES            R$ 5.10  R$ 5.86
                GO            R$ 4.46  R$ 6.04
                MA            R$ 4.96  R$ 5.60
                MG            R$ 4.44  R$ 6.02
                MS            R$ 4.56  R$ 5.82
                MT            R$ 4.12  R$ 5.81
                PA            R$ 5.33  R$ 5.92
                PB            R$ 4.90  R$ 5.51
                PE            R$ 5.08  R$ 5.79
                PI            R$ 5.06  R$ 6.11
                PR            R$ 4.36  R$ 5.52
                RJ            R$ 5.31  R$ 6.30
                RN            R$ 5.53  R$ 6.16
                RO            R$ 5.08  R$ 5.85
                RR            R$ 4.87  R$ 5.42
                RS            R$ 5.81  R$ 6.03
                SC            R$ 5.03  R$ 5.50
                SE            R$ 5.05  R$ 5.69
                SP            R$ 4.15  R$ 5.46
                TO            R$ 5.13  R$ 5.93
Valor de Compra AC                NaN      NaN
                AL                NaN      NaN
                AM                NaN      NaN
                AP                NaN      NaN
                BA                NaN      NaN
                CE                NaN      NaN
                DF                NaN      NaN
                ES                NaN      NaN
                GO                NaN      NaN
                MA                NaN      NaN
                MG                NaN      NaN
                MS                NaN      NaN
                MT                NaN      NaN
                PA                NaN      NaN
                PB                NaN      NaN
                PE                NaN      NaN
                PI                NaN      NaN
                PR                NaN      NaN
                RJ                NaN      NaN
                RN                NaN      NaN
                RO                NaN      NaN
                RR                NaN      NaN
                RS                NaN      NaN
                SC                NaN      NaN
                SE                NaN      NaN
                SP                NaN      NaN
                TO                NaN      NaN

Qual a região que possui o maior valor médio da gasolina?

In [ ]:
gasolina_max_regiao = df_copia[df_copia['Produto']=='GASOLINA'].groupby(['Região_Sigla', 'Produto']).agg( {"Valor_Venda":"mean"}).round(2).sort_values('Valor_Venda', ascending=False).head(1)
gasolina_max_regiao

                       Valor_Venda
Região_Sigla Produto
CO           GASOLINA          5.9

Qual a região que possui o menor valor médio do etanol?

In [ ]:
etanol_min_regiao = df_copia[df_copia['Produto']=='ETANOL'].groupby(['Região_Sigla', 'Produto']).agg( {"Valor_Venda":"mean"}).round(2).sort_values('Valor_Venda').head(1)
etanol_min_regiao

                      Valor_Venda
Região_Sigla Produto
SE           ETANOL          4.36